select * from users where userid = $1
or userid = $2
or userid = $3
or userid = $4
or userid = $5
or userid = $6
or userid = $7
or userid = $8
or userid = $9
or userid = $10
or userid = $11
or userid = $12
or userid = $13
or userid = $14
or userid = $15
or userid = $16
or userid = $17
or userid = $18
or userid = $19
or userid = $20
or userid = $21
or userid = $22
or userid = $23
or userid = $24
or userid = $25
order by viewers desc;--this seems really bad
